/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 🇧🇷 SamelCookies 🇧🇷 (https://sketchfab.com/ZamuelWarrior)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sanic-7c3ee34bda964ac6a88721de336a2f1b
Title: SANIC
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ItsSanicModel({...props}) {
     const group = useRef();
    const { nodes, materials, animations } = useGLTF("/assets/3d/classic_sonic.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[0, -1, 4]}
        rotation={[Math.PI / 2, 0.096, -1.658]}
        scale={[0.095, 0.073, 0.062]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_46.geometry}
          material={materials.rsMaterial1SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_47.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_48.geometry}
          material={materials.aj1CubeFBXASC046003SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_49.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_50.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_51.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_52.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_53.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_54.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_55.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_56.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_57.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_58.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_59.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG13}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_60.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG10}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_61.geometry}
          material={materials.aj1L_Air_J_outsoleSG_among_us_aj2aj2rsMaterial1SG11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_62.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG19}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_63.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_64.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group
        position={[-1.6, -1.867, 0.042]}
        rotation={[1.598, 0.051, 1.624]}
        scale={[-0.088, 0.095, 0.067]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_66.geometry}
          material={materials.rsMaterial1SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_67.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_68.geometry}
          material={materials.aj1CubeFBXASC046003SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_69.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_70.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_72.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_73.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_74.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_75.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_76.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_77.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_78.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_79.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG13}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_80.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG10}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_81.geometry}
          material={materials.aj1L_Air_J_outsoleSG_among_us_aj2aj2rsMaterial1SG11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_82.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG19}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_83.geometry}
          material={materials.among_us_aj2aj2rsMaterial1SG4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_84.geometry}
          material={materials['Material.002']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Fur_Material.001']}
        position={[0.064, -0.507, 0]}
        scale={0.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials['Material.007']}
        position={[0.212, -0.402, 0.574]}
        scale={0.274}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials['Fur_Material.001']}
        position={[0.111, 0.439, 0]}
        scale={0.165}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials['Fur_Material.001']}
        position={[0.303, 1.129, 0]}
        scale={0.577}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials['Material.005']}
        position={[0.042, 1.2, 0.154]}
        scale={0.267}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials['Material.004']}
        position={[0.489, 1.201, 0.128]}
        scale={0.315}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials['Material.001']}
        position={[-0.019, 1.443, -0.047]}
        rotation={[-0.371, 0.06, -1.315]}
        scale={[0.101, 0.326, 0.171]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials['Material.001']}
        position={[-0.255, 1.166, -0.047]}
        rotation={[-0.343, -0.157, -0.751]}
        scale={[0.079, 0.257, 0.135]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials['Material.001']}
        position={[-0.061, 0.59, -0.047]}
        rotation={[-0.323, -0.176, -0.671]}
        scale={[0.036, 0.115, 0.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials['Material.001']}
        position={[-0.397, 0.39, -0.047]}
        rotation={[-0.371, 0.06, -1.315]}
        scale={[0.039, 0.126, 0.066]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials['Material.007']}
        position={[0.335, 0.905, 0.405]}
        rotation={[0.003, -0.031, 0.018]}
        scale={[0.111, 0.132, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials['Material.003']}
        position={[0.251, 1.048, 0.454]}
        rotation={[0.488, 0.008, 0.044]}
        scale={[0.054, 0.026, 0.029]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials['Material.007']}
        position={[0.402, 0.879, 0.376]}
        rotation={[0.003, -0.031, 0.018]}
        scale={[0.1, 0.119, 0.036]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials['Fur_Material.001']}
        position={[-0.438, 0.303, 0]}
        rotation={[0, 0, -0.389]}
        scale={0.177}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials.HAZMAT_SUIT}
        position={[2.023, -0.311, 0.073]}
        rotation={[1.796, -0.895, 0.041]}
        scale={[-0.366, 0.421, 0.387]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials['Fur_Material.001']}
        position={[1.047, 0.235, 0]}
        rotation={[0, 0, -0.862]}
        scale={0.048}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials.HAZMAT_SUIT}
        position={[-1.647, -0.419, 0.054]}
        rotation={[2.699, 0.107, -1.075]}
        scale={[0.385, 0.529, 0.512]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials['Material.001']}
        position={[-0.552, -0.161, -0.047]}
        rotation={[-0.371, 0.06, -1.315]}
        scale={[0.051, 0.164, 0.086]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials['Material.001']}
        position={[-0.622, -0.401, -0.047]}
        rotation={[-0.375, 0.024, -1.224]}
        scale={[0.051, 0.164, 0.086]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials['Material.001']}
        position={[0.155, -0.762, -0.54]}
        rotation={[-1.776, -1.291, -2.169]}
        scale={[0.041, 0.103, 0.134]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials['Fur_Material.001']}
        position={[0.554, -0.904, 0.045]}
        rotation={[0, 0, 0.372]}
        scale={[0.083, 0.083, 0.139]}
      />
    </group>
  )
}



