/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Seafoam (https://sketchfab.com/seafoam)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/smol-ame-in-an-upcycled-terrarium-hololiveen-490cecc249d242188fda5ad3160a4b24
Title: Smol Ame in an Upcycled Terrarium [HololiveEn]
*/

import React, { useRef, useEffect, useState } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';
import {a} from '@react-spring/three';



export default function Landing(props) {
  
  const group = useRef();
  const { nodes: jakeNodes, materials: jakeMaterials } = useGLTF(
    "/assets/3d/jake_el_perro.glb"
  );
   const { nodes: CourageNodes, materials: CourageMaterials } = useGLTF(
    "/assets/3d/courage_eggplant.glb"
  );
  const { nodes, materials, animations } = useGLTF("/assets/3d/smol-ame.glb");
  const { actions, names } = useAnimations(animations, group);
  const [hovered, setHovered] = useState(false);
  const [ameHovered, setAmeHovered] = useState(false);
  const [jakeHovered, setJakeHovered] = useState(false);
  const [pekoHovered, setPekoHovered] = useState(false);
  const [courageHovered, setCourageHovered] = useState(false);
  const anyHovered = ameHovered || jakeHovered || pekoHovered || courageHovered;

   useEffect(() => {
    if (names.length > 0) {
      actions[names[0]]?.play();
    }
  }, [actions, names]);

   useEffect(() => {
    const action = actions[names[0]];
    if (!action) return;
    anyHovered ? action.paused = true : action.paused = false;
  }, [anyHovered, actions, names]);

  // Slight rotation
  useFrame((state, delta) => {
    if (!anyHovered) {
    group.current.rotation.y += delta * 0.2;
  }
    
  });

 

  return ( 
    <a.group ref={group} {...props}  >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="pasokon_1" >
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.pasokon}
                />
                <mesh
                  name="Object_5"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_5.geometry}
                  material={materials.terrarium1}
                />
              </group>
              <group name="amelia_37" position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]} scale={ameHovered ? 1.3 : 1}
      onPointerOver={() => setAmeHovered(true)}
      onPointerOut={() => setAmeHovered(false)}> 
        
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_10"
                    geometry={nodes.Object_10.geometry}
                    material={materials.terrarium1ame}
                    skeleton={nodes.Object_10.skeleton}
                  />
                  <skinnedMesh
                    name="Object_12"
                    geometry={nodes.Object_12.geometry}
                    material={materials.terrarium1ameoutline}
                    skeleton={nodes.Object_12.skeleton}
                  />
                  <skinnedMesh
                    name="Object_14"
                    geometry={nodes.Object_14.geometry}
                    material={materials.terrarium1ame}
                    skeleton={nodes.Object_14.skeleton}
                  />
                  <skinnedMesh
                    name="Object_16"
                    geometry={nodes.Object_16.geometry}
                    material={materials.terrarium1ameoutline}
                    skeleton={nodes.Object_16.skeleton}
                  />
                  <skinnedMesh
                    name="Object_18"
                    geometry={nodes.Object_18.geometry}
                    material={materials.terrarium1ame}
                    skeleton={nodes.Object_18.skeleton}
                  />
                  <skinnedMesh
                    name="Object_19"
                    geometry={nodes.Object_19.geometry}
                    material={materials.terrarium1ameoutline}
                    skeleton={nodes.Object_19.skeleton}
                  />
                  <skinnedMesh
                    name="Object_21"
                    geometry={nodes.Object_21.geometry}
                    material={materials.terrarium1ameoutline}
                    skeleton={nodes.Object_21.skeleton}
                  />
                  <skinnedMesh
                    name="Object_23"
                    geometry={nodes.Object_23.geometry}
                    material={materials.terrarium1ame}
                    skeleton={nodes.Object_23.skeleton}
                  />
                  <skinnedMesh
                    name="Object_25"
                    geometry={nodes.Object_25.geometry}
                    material={materials.terrarium1ame}
                    skeleton={nodes.Object_25.skeleton}
                  />
                  <skinnedMesh
                    name="Object_27"
                    geometry={nodes.Object_27.geometry}
                    material={materials.terrarium1ameoutline}
                    skeleton={nodes.Object_27.skeleton}
                  />
                  <skinnedMesh
                    name="Object_29"
                    geometry={nodes.Object_29.geometry}
                    material={materials.terrarium1ame}
                    skeleton={nodes.Object_29.skeleton}
                  />
                  <skinnedMesh
                    name="Object_31"
                    geometry={nodes.Object_31.geometry}
                    material={materials.terrarium1ameoutline}
                    skeleton={nodes.Object_31.skeleton}
                  />
                  <skinnedMesh
                    name="Object_33"
                    geometry={nodes.Object_33.geometry}
                    material={materials.terrarium1ame}
                    skeleton={nodes.Object_33.skeleton}
                  />
                  <skinnedMesh
                    name="Object_35"
                    geometry={nodes.Object_35.geometry}
                    material={materials.terrarium1ameoutline}
                    skeleton={nodes.Object_35.skeleton}
                  />
                  <skinnedMesh
                    name="Object_37"
                    geometry={nodes.Object_37.geometry}
                    material={materials.terrarium1ame}
                    skeleton={nodes.Object_37.skeleton}
                    morphTargetDictionary={nodes.Object_37.morphTargetDictionary}
                    morphTargetInfluences={nodes.Object_37.morphTargetInfluences}
                  />
                  <skinnedMesh
                    name="Object_39"
                    geometry={nodes.Object_39.geometry}
                    material={materials.terrarium1ame}
                    skeleton={nodes.Object_39.skeleton}
                  />
                  <skinnedMesh
                    name="Object_41"
                    geometry={nodes.Object_41.geometry}
                    material={materials.terrarium1ameoutline}
                    skeleton={nodes.Object_41.skeleton}
                  />
                  <group name="armies_21" />
                  <group name="armies001_22" />
                  <group name="bode_23" />
                  <group name="bode001_24" />
                  <group name="Cylinder003_25" />
                  <group name="Cylinder004_26" />
                  <group name="eyea_27" />
                  <group name="feets_28" />
                  <group name="feets001_29" />
                  <group name="guitar_30" />
                  <group name="guitar001_31" />
                  <group name="hair_32" />
                  <group name="hairoutline_33" />
                  <group name="mouf_34" />
                  <group name="nogging_35" />
                  <group name="nogging001_36" />
                </group>
              </group>
              <group
                name="isopod002_49"
                position={[0, 0.864, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={pekoHovered ? 0.1 : 0.073}
      onPointerOver={() => setPekoHovered(true)}
      onPointerOut={() => setPekoHovered(false)}
                >
                <group name="GLTF_created_1">
                  <primitive object={nodes.GLTF_created_1_rootJoint} />
                  <skinnedMesh
                    name="Object_65"
                    geometry={nodes.Object_65.geometry}
                    material={materials.terrarium1}
                    skeleton={nodes.Object_65.skeleton}
                  />
                  <skinnedMesh
                    name="Object_67"
                    geometry={nodes.Object_67.geometry}
                    material={materials.terrarium1ameoutline}
                    skeleton={nodes.Object_67.skeleton}
                  />
                  <group name="isopod_47" />
                  <group name="isopod001_48" />
                </group>
              </group>
            </group>
          </group>
        </group>

        
      </group>

      {/* Jake*/}
      <group
        rotation={[-Math.PI / 2, 0, 0]}
        scale={jakeHovered  ? 0.30 : 0.25}
        position={[0.7, 2.35, 0.24]} // move Jake a bit to the side
        onPointerOver={() => setJakeHovered(true)}
      onPointerOut={() => setJakeHovered(false)}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={jakeNodes.Cube002_Material002_0.geometry}
            material={jakeMaterials["Material.002"]}
            position={[98.371, 33.056, 15.837]}
            rotation={[-Math.PI / 2, -0.415, 0]}
            scale={[12.691, 32.752, 32.752]}
            
          />
        </group>
      </group>

      {/* courage*/}
      <group rotation={[1.576, 0, 0.7]} scale={courageHovered  ? 0.65 :0.6}
      onPointerOver={() => setCourageHovered(true)}
      onPointerOut={() => setCourageHovered(false)}
      position={[-1.42, 0, 0]} >
        <group rotation={[-Math.PI, 0, 0]} scale={0.025}>
          <mesh
            castShadow
            receiveShadow
            geometry={CourageNodes.Coraje_Coraje__0.geometry}
            material={CourageMaterials.Coraje}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={CourageNodes.Object_Outline_0.geometry}
            material={CourageMaterials.Outline}
          />
        </group>
      </group>
    </a.group>
  )
}


