

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Hannes Delbeke (https://sketchfab.com/han)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fantasy-sky-background-15c79bb2fc1147128039fe4ff90fd5a0
Title: Fantasy Sky Background
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export  default function Sky(props) {

  const { nodes, materials } = useGLTF("/assets/3d/free_-_skybox_anime_sky.glb");
  return (
      <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere__0.geometry}
          material={materials['Scene_-_Root']}
          rotation={[-Math.PI / 2, -2, -2]}
          scale={50000}
        />
      </group>
    </group>
  )
}


