

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Hannes Delbeke (https://sketchfab.com/han)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fantasy-sky-background-15c79bb2fc1147128039fe4ff90fd5a0
Title: Fantasy Sky Background
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export  default function Sky(props) {

  const group = useRef();

 

  const { nodes, materials } = useGLTF("/assets/3d/skybox.glb");

    useFrame((state, delta) => {
    if (group.current) {
      group.current.rotation.y += delta * 0.1; // Adjust speed here
    }
  });
  
  return (
         <group  ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Skybox_mat}
        scale={2}
        rotation={[Math.PI / 8,0, 0]}
      />
    </group>
  )
}


